import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

export default function HowToPlay() {
  return (
    <div className="min-h-screen bg-background p-6 md:p-8 overflow-y-auto">
      <div className="max-w-3xl mx-auto space-y-6">
        <header className="flex items-center justify-between border-b border-primary/20 pb-4">
          <div>
            <h1 className="text-3xl font-bold text-primary font-mono drop-shadow-[0_0_8px_rgba(0,255,128,0.5)]">
              TACTICAL MANUAL
            </h1>
            <p className="text-muted-foreground font-mono text-sm mt-1">
              Briefing for new commanders — remake of classic Metal Marines doctrine
            </p>
          </div>
          <Link href="/">
            <Button variant="outline" className="font-mono border-primary/30 text-primary hover:bg-primary/10">
              RETURN
            </Button>
          </Link>
        </header>

        <div className="space-y-5 text-foreground/90">
          <Card className="bg-card/50 border-primary/20">
            <CardContent className="p-6 space-y-3">
              <h2 className="text-lg font-bold text-secondary font-mono uppercase">01 :: Objective</h2>
              <p className="text-sm leading-relaxed">
                Two islands across a contested sea. You may field up to <b>three Headquarters</b>.
                Defeat only comes when your <b>last</b> base falls — same for the enemy.
                Ground forces cannot swim: everything crosses by missile or transport pod.
              </p>
            </CardContent>
          </Card>

          <Card className="bg-card/50 border-primary/20">
            <CardContent className="p-6 space-y-3">
              <h2 className="text-lg font-bold text-secondary font-mono uppercase">02 :: Resources</h2>
              <ul className="text-sm space-y-2">
                <li>
                  <span className="text-yellow-400 font-bold">War Funds</span> — used to
                  build everything. Generated by Supply Depots and your HQ.
                </li>
                <li>
                  <span className="text-cyan-400 font-bold">Energy</span> — required to
                  power weapons, mech bays and radars. Generated by Energy Plants.
                </li>
                <li>
                  <span className="text-amber-300 font-bold">Factory</span> — speeds construction,
                  fields garrison APCs against landed Marines, and launches gunship strafes.
                  Use Factory doctrine (Auto / APC / Gunship / Hold) once a Factory is online.
                  Set gunship strike priority (Auto / HQ / AA / Energy / Missile) like Marine fire modes.
                  <b className="text-lime-300"> AA Batteries</b> auto-engage hostile gunships — thicken
                  your AA screen when radar shows craft over base.
                </li>
              </ul>
            </CardContent>
          </Card>

          <Card className="bg-card/50 border-primary/20">
            <CardContent className="p-6 space-y-3">
              <h2 className="text-lg font-bold text-secondary font-mono uppercase">03 :: Buildings</h2>
              <p className="text-xs text-muted-foreground font-mono">
                Build palette tabs: Base · Intel · Weapons · Eco
              </p>
              <ul className="text-sm space-y-1.5">
                <li>
                  <span className="text-cyan-300 font-bold uppercase tracking-wide text-xs">Base</span>{" "}
                  — <b className="text-red-400">HQ</b> (up to 3; last standing wins),{" "}
                  <b className="text-cyan-400">Energy Plant</b>,{" "}
                  <b className="text-yellow-400">Supply Depot</b>,{" "}
                  <b className="text-amber-300">Factory</b>,{" "}
                  <b className="text-slate-300">Dummy Base / Cover</b>
                </li>
                <li>
                  <span className="text-purple-300 font-bold uppercase tracking-wide text-xs">Intel</span>{" "}
                  — <b className="text-purple-400">Radar Array</b> (+5% AA hit each; base 50%, cap 100%),{" "}
                  <b className="text-fuchsia-400">Radar Jammer</b>,{" "}
                  <b className="text-amber-300">Tunnel Gate / Seismic</b> (mid-campaign)
                </li>
                <li>
                  <span className="text-red-300 font-bold uppercase tracking-wide text-xs">Weapons</span>{" "}
                  — <b className="text-orange-400">Missile Silo</b>,{" "}
                  <b className="text-rose-300">ICBM Silo (3×3 intact)</b>,{" "}
                  <b className="text-sky-300">EMP Cannon</b>,{" "}
                  <b className="text-red-400">Mech Bay</b> (max 3 Marines),{" "}
                  <b className="text-lime-300">AA Battery</b>,{" "}
                  <b className="text-amber-400">Gun Turret / Gun Pod</b>,{" "}
                  <b className="text-slate-400">Land Mine</b>
                </li>
                <li>
                  <span className="text-lime-300 font-bold uppercase tracking-wide text-xs">Eco</span>{" "}
                  — <b className="text-lime-300">Destabilizer / Weather / Biosphere</b> unlock as optional
                  campaign branches once classic doctrine is secure.
                </li>
              </ul>
            </CardContent>
          </Card>

          <Card className="bg-card/50 border-primary/20">
            <CardContent className="p-6 space-y-3">
              <h2 className="text-lg font-bold text-secondary font-mono uppercase">04 :: Combat</h2>
              <ul className="text-sm space-y-2">
                <li><b className="text-red-400">ICBM</b> — heavy splash; needs an intact ICBM Silo.</li>
                <li><b className="text-violet-300">Dummy</b> — bait AA / scout fog.</li>
                <li><b className="text-lime-300">AA Missile</b> — manual intercept.</li>
                <li><b className="text-orange-300">Marine Drop</b> — Gunner I or II with NORMAL / Anti-MMR / Anti-POD modes.</li>
                <li><b className="text-sky-300">EMP / Tunnel Buster</b> — disable grids or collapse tunnels.</li>
              </ul>
              <p className="text-xs text-muted-foreground">
                Anti-MMR: +50% vs enemy Marines, −50% vs Gun Pods. Anti-POD: inverted. Choose loadout before launching.
              </p>
            </CardContent>
          </Card>

          <Card className="bg-card/50 border-primary/20">
            <CardContent className="p-6 space-y-3">
              <h2 className="text-lg font-bold text-secondary font-mono uppercase">05 :: Controls</h2>
              <ul className="text-sm space-y-1.5 font-mono">
                <li>Left island — place buildings · Right island — fire weapons</li>
                <li>ESC / Right-click — cancel selection</li>
                <li>V — toggle surface / underground view</li>
                <li>SPACE — pause</li>
                <li>B / F / G / I / D / C — HQ, Factory, Gun Pod, ICBM Silo, Dummy Base, Dummy Cover</li>
                <li>1–0 and - = [ ] \ — remaining build palette hotkeys</li>
                <li>Q–Y — strike weapons (ICBM, Dummy, AA, Marine Drop, EMP, Buster)</li>
                <li>Z / X — Gunner I / Gunner II · N / M / P — Normal / Anti-MMR / Anti-POD</li>
                <li>O / A / S / H — Factory Auto / APC / Gunship / Hold</li>
                <li>U / J / K / L / ; — Gunship strike Auto / HQ / AA / Energy / Missile</li>
              </ul>
            </CardContent>
          </Card>

          <Card className="bg-card/50 border-primary/20">
            <CardContent className="p-6 space-y-3">
              <h2 className="text-lg font-bold text-secondary font-mono uppercase">06 :: Theater Command</h2>
              <p className="text-sm leading-relaxed">
                <b className="text-primary">NEW CAMPAIGN</b> opens{" "}
                <b className="text-cyan-300">Theater Command</b> — a Pacific sector map of twenty
                operations from Cadet Voss to NULL. Nodes read{" "}
                <b className="text-emerald-300">Available</b>,{" "}
                <b className="text-cyan-300">Secured</b>, or{" "}
                <b className="text-slate-400">Classified</b>. Select a sector to open the combat
                briefing; Mission List remains a fallback roster.
              </p>
              <p className="text-sm leading-relaxed text-muted-foreground">
                Early sectors teach economy and multi-base defense. Mid campaign brings Gun Pods,
                Dummy Bases, and ICBM Silos. Late sectors 13–20 stay hard (difficulty ≥5) with
                authored choke maps through the finale. Tunnel and ecology systems unlock as
                optional branches once classic Metal Marines doctrine is secure. Theater and
                Mission List skirmish generation accept difficulty 1–5 plus an optional seed for
                rematches.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
