import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

export default function HowToPlay() {
  return (
    <div className="min-h-screen bg-background p-6 md:p-8 overflow-y-auto">
      <div className="max-w-3xl mx-auto space-y-6">
        <header className="flex items-center justify-between border-b border-primary/20 pb-4">
          <div>
            <h1 className="text-3xl font-bold text-primary font-mono drop-shadow-[0_0_8px_rgba(0,255,128,0.5)]">
              TACTICAL MANUAL
            </h1>
            <p className="text-muted-foreground font-mono text-sm mt-1">
              Briefing for new commanders — remake of classic Metal Marines doctrine
            </p>
          </div>
          <Link href="/">
            <Button variant="outline" className="font-mono border-primary/30 text-primary hover:bg-primary/10">
              RETURN
            </Button>
          </Link>
        </header>

        <div className="space-y-5 text-foreground/90">
          <Card className="bg-card/50 border-primary/20">
            <CardContent className="p-6 space-y-3">
              <h2 className="text-lg font-bold text-secondary font-mono uppercase">01 :: Objective</h2>
              <p className="text-sm leading-relaxed">
                Two islands across a contested sea. You may field up to <b>three Headquarters</b>.
                Defeat only comes when your <b>last</b> base falls — same for the enemy.
                Ground forces cannot swim: everything crosses by missile or transport pod.
              </p>
            </CardContent>
          </Card>

          <Card className="bg-card/50 border-primary/20">
            <CardContent className="p-6 space-y-3">
              <h2 className="text-lg font-bold text-secondary font-mono uppercase">02 :: Resources</h2>
              <ul className="text-sm space-y-2">
                <li>
                  <span className="text-yellow-400 font-bold">War Funds</span> — used to
                  build everything. Generated by Supply Depots and your HQ.
                </li>
                <li>
                  <span className="text-cyan-400 font-bold">Energy</span> — required to
                  power weapons, mech bays and radars. Generated by Energy Plants.
                </li>
                <li>
                  <span className="text-amber-300 font-bold">Factory</span> — each active Factory
                  speeds construction across your island.
                </li>
              </ul>
            </CardContent>
          </Card>

          <Card className="bg-card/50 border-primary/20">
            <CardContent className="p-6 space-y-3">
              <h2 className="text-lg font-bold text-secondary font-mono uppercase">03 :: Buildings</h2>
              <ul className="text-sm space-y-1.5">
                <li><b className="text-red-400">Headquarters</b> — up to 3 bases. Last base standing wins.</li>
                <li><b className="text-cyan-400">Energy Plant</b> — generates Energy.</li>
                <li><b className="text-yellow-400">Supply Depot</b> — generates Funds.</li>
                <li><b className="text-amber-300">Factory</b> — accelerates build timers.</li>
                <li><b className="text-slate-300">Dummy Base / Cover</b> — decoy HQ and radar concealment.</li>
                <li><b className="text-purple-400">Radar Array</b> — reveals the enemy island; each Radar adds +5% AA hit chance (base 50%, cap 100%).</li>
                <li><b className="text-fuchsia-400">Radar Jammer</b> — creates false signatures and complicates intercepts.</li>
                <li><b className="text-orange-400">Missile Silo</b> — fires Dummies, AA, and Tunnel Busters.</li>
                <li><b className="text-rose-300">ICBM Silo (3×3)</b> — required for ICBMs; the whole footprint must stay intact.</li>
                <li><b className="text-sky-300">EMP Cannon</b> — disables clustered enemy systems for a short window.</li>
                <li><b className="text-red-400">Mech Bay</b> — launches transport pods (max 3 Marines assaulting).</li>
                <li><b className="text-lime-300">AA Battery</b> — auto-intercepts; accuracy scales with Radar count.</li>
                <li><b className="text-amber-400">Gun Turret / Gun Pod</b> — anti-mech defenses (Pods are classic bunkers).</li>
                <li><b className="text-slate-400">Land Mine</b> — hidden trap under enemy mechs.</li>
                <li><b className="text-amber-300">Tunnel Gate / Seismic</b> — mid-campaign subterranean warfare.</li>
                <li><b className="text-lime-300">Destabilizer / Weather / Biosphere</b> — ecological warfare unlocks.</li>
              </ul>
            </CardContent>
          </Card>

          <Card className="bg-card/50 border-primary/20">
            <CardContent className="p-6 space-y-3">
              <h2 className="text-lg font-bold text-secondary font-mono uppercase">04 :: Combat</h2>
              <ul className="text-sm space-y-2">
                <li><b className="text-red-400">ICBM</b> — heavy splash; needs an intact ICBM Silo.</li>
                <li><b className="text-violet-300">Dummy</b> — bait AA / scout fog.</li>
                <li><b className="text-lime-300">AA Missile</b> — manual intercept.</li>
                <li><b className="text-orange-300">Marine Drop</b> — Gunner I or II with NORMAL / Anti-MMR / Anti-POD modes.</li>
                <li><b className="text-sky-300">EMP / Tunnel Buster</b> — disable grids or collapse tunnels.</li>
              </ul>
              <p className="text-xs text-muted-foreground">
                Anti-MMR: +50% vs enemy Marines, −50% vs Gun Pods. Anti-POD: inverted. Choose loadout before launching.
              </p>
            </CardContent>
          </Card>

          <Card className="bg-card/50 border-primary/20">
            <CardContent className="p-6 space-y-3">
              <h2 className="text-lg font-bold text-secondary font-mono uppercase">05 :: Controls</h2>
              <ul className="text-sm space-y-1.5 font-mono">
                <li>Left island — place buildings · Right island — fire weapons</li>
                <li>ESC / Right-click — cancel selection</li>
                <li>V — toggle surface / underground view</li>
                <li>SPACE — pause</li>
              </ul>
            </CardContent>
          </Card>

          <Card className="bg-card/50 border-primary/20">
            <CardContent className="p-6 space-y-3">
              <h2 className="text-lg font-bold text-secondary font-mono uppercase">06 :: Campaign</h2>
              <p className="text-sm leading-relaxed">
                Twenty operations stretch from Cadet Voss to NULL. Early missions teach economy and
                multi-base defense. Mid campaign introduces Gun Pods, Dummy Bases, and ICBM Silos.
                Tunnel and ecology systems unlock as optional branches once the classic fantasy is secure.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
